language: cpp

# Ubuntu Focal 20.04
os: linux
dist: bionic

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "mEyGwQuPZEe9H80m646YeRr3SHQVPNQW+3c8iPl1S5C5Opu6xaH+d4rP6TMD3yUsCEQbJXhkjyU3fgx8+v0tkfrJ6A20/7iCwQJGzP56EWYTQsbw/q+d3ugTJJVnu+cb379zfsVjvSBL/rthjxYY3km/l/cU+OweRssTjsU8a65Mrrad/cRh6CH6nDSJdQtTnhyz7uUj0XV5dYi2YNkfAuGjMY7k0Sr7Pdv2mRB9zylmmO2HyY75V7il63TJ8SJ4gLJ3T/nbIrYol4mi2dhjcIJpPfj3uIKgTJpRu6eXLVuZLIo9wuPnFeGgVMqUI566ZIMaqofeIo4+m9o0I8nkojIblO7DWZCv+du3pIchDXVEafDQAOUxwMNA9DjCN26z9g1cVrzR6G5vkEVcw483YiKvQKg8gW9ulFglFa5pZ+vksIvFxvT7HcXKi205KvERJayndQssd1/5RliMQlVlIhVHLygbRXDzzD3UC0r1waIHagaUo+DSvxkx5lauhpFC4fyUURV/LM88+z3RZxpcmzRQgtJc9glaVqkOxdH8/KeIsZluU1bJpJoAM0m63nW9qK0EamAbjDjB5hD9YMYGhE9SLCPwvw4ypmu5TfZ7HveJh3geybHnynoHzl5Z4bu1HEeq4ciNcsySBempPqWoh/SnmrFJhZL1wpZSeq6J1uY="

before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  apt:
    packages: [ninja-build]
  coverity_scan:
    project:
      name: "clover2123/escargot"
      description: "Memory optimized JavaScript engine for mid-range devices."
    build_command_prepend: "cmake -H./ -Bout/release -DESCARGOT_HOST=linux -DESCARGOT_ARCH=x64 -DESCARGOT_MODE=release -DESCARGOT_OUTPUT=shell_test -GNinja"
    build_command: "ninja -Cout/release"
    branch_pattern: master

script:
  - cmake -H./ -Bout/release -DESCARGOT_HOST=linux -DESCARGOT_ARCH=x64 -DESCARGOT_MODE=release -DESCARGOT_OUTPUT=shell_test -GNinja
#- ninja -Cout/release

notifications:
  email: false
