name: ES-Actions

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  RUNNER: tools/run-tests.py

jobs:
  check-tidy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install Packages
      run: |
        sudo add-apt-repository "deb http://mirrors.kernel.org/ubuntu/ focal main universe"
        sudo apt-get update
        sudo apt-get install -y clang-format-6.0
    - name: Test
      run: tools/check_tidy.py

  build-on-macos:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install Packages
      run: |
        brew update
        brew install cmake ninja pkg-config icu4c
    - name: Build x64
      env:
        BUILD_OPTIONS: -DESCARGOT_MODE=debug -DESCARGOT_LIBICU_SUPPORT_WITH_DLOPEN=OFF -DESCARGOT_WASM=ON -DESCARGOT_TEMPORAL=ON -DESCARGOT_TCO=ON -DESCARGOT_TEST=ON -DESCARGOT_OUTPUT=shell -GNinja
      run: |
        export PKG_CONFIG_PATH="/usr/local/opt/icu4c/lib/pkgconfig"
        cmake -H. -Bout/mac/x64 $BUILD_OPTIONS
        ninja -Cout/mac/x64
        ./tools/run-tests.py --engine="./out/mac/x64/escargot" new-es

  build-by-clang:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install Packages
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build gcc-multilib g++-multilib libicu-dev
    - name: Build x86
      env:
        BUILD_OPTIONS: -DCMAKE_SYSTEM_NAME=Linux -DCMAKE_SYSTEM_PROCESSOR=x86 -DESCARGOT_MODE=debug -DESCARGOT_WASM=ON -DESCARGOT_TEMPORAL=ON -DESCARGOT_TCO=ON -DESCARGOT_TEST=ON -DESCARGOT_OUTPUT=shell -GNinja
      run: |
        CC=clang CXX=clang++ cmake -H. -Bout/clang/x86 $BUILD_OPTIONS
        ninja -Cout/clang/x86
    - name: Build x64
      env:
        BUILD_OPTIONS: -DESCARGOT_MODE=debug -DESCARGOT_WASM=ON -DESCARGOT_TEMPORAL=ON -DESCARGOT_TCO=ON -DESCARGOT_TEST=ON -DESCARGOT_OUTPUT=shell -GNinja
      run: |
        CC=clang CXX=clang++ cmake -H. -Bout/clang/x64 $BUILD_OPTIONS
        ninja -Cout/clang/x64
        ./tools/run-tests.py --engine="./out/clang/x64/escargot" new-es

  test-on-windows-clang-cl:
    runs-on: windows-2022
    strategy:
      matrix:
        # clang-cl with cannot generate c++ exception code well
        # if clang-cl bug fixed, we can add x64
        arch: [
          {cpu: "x86", flag: "-m32"}
          # , {cpu: "x64", flag: ""}
          ]
    steps:
    - name: Set git cllf config
      run: |
        git config --global core.autocrlf input
        git config --global core.eol lf
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: szenius/set-timezone@v1.2
      with:
        timezoneWindows: "Pacific Standard Time"
    - uses: lukka/get-cmake@latest
    - uses: GuillaumeFalourd/setup-windows10-sdk-action@v1.11
      with:
        sdk-version: 20348
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install msvc redist package
      run: |
        (new-object System.Net.WebClient).DownloadFile('https://github.com/abbodi1406/vcredist/releases/download/v0.73.0/VisualCppRedist_AIO_x86_x64.exe','VisualCppRedist_AIO_x86_x64.exe')
        .\VisualCppRedist_AIO_x86_x64.exe /y
    - uses: ilammy/msvc-dev-cmd@v1.12.1
      with:
        arch: ${{ matrix.arch.cpu }}
        sdk: "10.0.20348.0"
    - name: Build ${{ matrix.arch.cpu }} Release
      run: |
        CMake -DCMAKE_SYSTEM_NAME=Windows -DCMAKE_SYSTEM_VERSION:STRING="10.0" -DCMAKE_SYSTEM_PROCESSOR=${{ matrix.arch.cpu }} -Bout/ -DESCARGOT_OUTPUT=shell -DESCARGOT_LIBICU_SUPPORT=ON -DESCARGOT_LIBICU_SUPPORT_WITH_DLOPEN=NO -DESCARGOT_WASM=ON -DESCARGOT_THREADING=ON -DESCARGOT_TCO=ON -DESCARGOT_TEST=ON -G Ninja -DCMAKE_C_COMPILER=clang-cl -DCMAKE_CXX_COMPILER=clang-cl -DCMAKE_BUILD_TYPE=release -DCMAKE_C_FLAGS="${{ matrix.arch.flag }}" -DCMAKE_CXX_FLAGS="${{ matrix.arch.flag }}"
        CMake --build out/ --config Release
    - name: Run octane
      run: |
        .\out\escargot.exe test.js
        copy test\octane\*.js
        dir
        .\out\escargot.exe run.js
    # clang-cl with cannot generate c++ exception code well. if clang-cl bug fixed, we can enable test262
    # - name: Run test262
    #   run: |
    #     set GC_FREE_SPACE_DIVISOR=1
    #     pip install chardet
    #     python tools\run-tests.py --engine=%cd%\out\escargot.exe test262 --extra-arg="--skip Temporal --skip intl402 --skip Atomics"
    #   shell: cmd
    - if: ${{ failure() }}
      uses: mxschmitt/action-tmate@v3
      timeout-minutes: 15

  test-on-windows-x86-x64:
    runs-on: windows-2022
    strategy:
      matrix:
        arch: [x86, x64]
    steps:
    - name: Set git cllf config
      run: |
        git config --global core.autocrlf input
        git config --global core.eol lf
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: szenius/set-timezone@v1.2
      with:
        timezoneWindows: "Pacific Standard Time"
    - uses: lukka/get-cmake@latest
    - uses: GuillaumeFalourd/setup-windows10-sdk-action@v1.11
      with:
        sdk-version: 20348
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install msvc redist package
      run: |
        (new-object System.Net.WebClient).DownloadFile('https://github.com/abbodi1406/vcredist/releases/download/v0.73.0/VisualCppRedist_AIO_x86_x64.exe','VisualCppRedist_AIO_x86_x64.exe')
        .\VisualCppRedist_AIO_x86_x64.exe /y
    - uses: ilammy/msvc-dev-cmd@v1.12.1
      with:
        arch: ${{ matrix.arch }}
        sdk: "10.0.20348.0"
    - name: Build ${{ matrix.arch }} Release
      run: |
        CMake -DCMAKE_SYSTEM_NAME=Windows -DCMAKE_SYSTEM_VERSION:STRING="10.0" -DCMAKE_SYSTEM_PROCESSOR=${{ matrix.arch }} -DESCARGOT_ARCH=${{ matrix.arch }} -Bout/ -DESCARGOT_OUTPUT=shell -DESCARGOT_LIBICU_SUPPORT=ON -DESCARGOT_LIBICU_SUPPORT_WITH_DLOPEN=OFF -DESCARGOT_WASM=ON -DESCARGOT_THREADING=ON -DESCARGOT_TCO=ON -DESCARGOT_TEST=ON -G Ninja -DCMAKE_C_COMPILER=cl -DCMAKE_CXX_COMPILER=cl -DCMAKE_BUILD_TYPE=release
        CMake --build out/ --config Release
    # windows internal ICU doesn't support Temporal and intl402 well
    # github action windows runner only have 2 CPUs. that's why I disable Atomics(timeout occured with some tests)
    - name: Run octane
      run: |
        .\out\escargot.exe test.js
        copy test\octane\*.js
        dir
        .\out\escargot.exe run.js
    - if: ${{ failure() }}
      uses: mxschmitt/action-tmate@v3
      timeout-minutes: 15

  build-on-windows-x64-uwp-x86-shared:
    runs-on: windows-2022
    steps:
    - name: Set git cllf config
      run: |
        git config --global core.autocrlf input
        git config --global core.eol lf
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: lukka/get-cmake@latest
    - uses: GuillaumeFalourd/setup-windows10-sdk-action@v1.11
      with:
        sdk-version: 20348
    - uses: ilammy/msvc-dev-cmd@v1.12.1
      with:
        arch: x64
        sdk: "10.0.20348.0"
        uwp: true
    - name: Build x64 UWP Release
      run: |
        CMake -G "Visual Studio 17 2022" -DCMAKE_SYSTEM_NAME=WindowsStore -DCMAKE_SYSTEM_VERSION:STRING="10.0" -DCMAKE_SYSTEM_PROCESSOR=x64 -Bout/win64_release_uwp/ -DESCARGOT_OUTPUT=shell -DESCARGOT_LIBICU_SUPPORT=ON -DESCARGOT_LIBICU_SUPPORT_WITH_DLOPEN=OFF -DESCARGOT_TEST=ON
        cmake --build out\win64_release_uwp --config Release
      shell: cmd
    - uses: ilammy/msvc-dev-cmd@v1.12.1
      with:
        arch: x86
        sdk: "10.0.20348.0"
    - name: Build x86 DLL Release
      run: |
        CMake -DCMAKE_SYSTEM_NAME=Windows -DCMAKE_SYSTEM_VERSION:STRING="10.0" -DCMAKE_SYSTEM_PROCESSOR=x86 -Bout/win32_release_shared/ -DESCARGOT_OUTPUT=shared_lib -DESCARGOT_LIBICU_SUPPORT=ON -DESCARGOT_LIBICU_SUPPORT_WITH_DLOPEN=OFF -DESCARGOT_THREADING=ON -DESCARGOT_TCO=ON -DESCARGOT_TEST=ON -G Ninja -DCMAKE_C_COMPILER=cl -DCMAKE_CXX_COMPILER=cl -DCMAKE_BUILD_TYPE=release
        CMake --build out/win32_release_shared --config Release
      shell: cmd
    - if: ${{ failure() }}
      uses: mxschmitt/action-tmate@v3
      timeout-minutes: 15

  build-test-wasmjs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install Packages
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build gcc-multilib g++-multilib
    - name: Build x86
      env:
        BUILD_OPTIONS: -DCMAKE_SYSTEM_NAME=Linux -DCMAKE_SYSTEM_PROCESSOR=x86 -DESCARGOT_MODE=debug -DESCARGOT_WASM=ON -DESCARGOT_TEMPORAL=ON -DESCARGOT_TCO=ON -DESCARGOT_TEST=ON -DESCARGOT_OUTPUT=shell -GNinja
      run: |
        cmake -H. -Bout/wasm/x86 $BUILD_OPTIONS
        ninja -Cout/wasm/x86
    - name: Build x64
      env:
        BUILD_OPTIONS: -DESCARGOT_MODE=debug -DESCARGOT_WASM=ON -DESCARGOT_TEMPORAL=ON -DESCARGOT_TCO=ON -DESCARGOT_TEST=ON -DESCARGOT_OUTPUT=shell -GNinja
      run: |
        cmake -H. -Bout/wasm/x64 $BUILD_OPTIONS
        ninja -Cout/wasm/x64
    - name: Run x86 test
      run: $RUNNER --arch=x86 --engine="$GITHUB_WORKSPACE/out/wasm/x86/escargot" wasm-js
    - name: Run x64 test
      run: $RUNNER --arch=x86_64 --engine="$GITHUB_WORKSPACE/out/wasm/x64/escargot" wasm-js
