name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

env:
  RUNNER: tools/run-tests.py
  BUILD_OPTIONS: -DESCARGOT_MODE=release -DESCARGOT_TCO=ON -DESCARGOT_TEST=ON -DESCARGOT_OUTPUT=shell -GNinja

jobs:
  build-mac64:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install Packages
      run: |
        brew update
        brew install ninja icu4c
    - name: Build x64
      run: |
        # check cpu
        sysctl -a | grep machdep.cpu
        # add icu path to pkg_config_path
        export PKG_CONFIG_PATH="/usr/local/opt/icu4c/lib/pkgconfig:$PKG_CONFIG_PATH"
        cmake -H. -Bout/ $BUILD_OPTIONS
        ninja -Cout/
    - name: Check
      run: |
        file out/escargot
        strip out/escargot
        $RUNNER --engine="./out/escargot" new-es
        mv out/escargot out/escargot-mac64
    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: mac64-result
        path: out/escargot-mac64

  build-mac64arm:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install Packages
      run: |
        brew update
        brew install ninja icu4c
    - name: Build arm64
      run: |
        # check cpu
        sysctl -a | grep machdep.cpu
        # add icu path to pkg_config_path
        export PKG_CONFIG_PATH="/opt/homebrew/opt/icu4c/lib/pkgconfig:$PKG_CONFIG_PATH"
        cmake -H. -Bout/ $BUILD_OPTIONS
        ninja -Cout/
    - name: Check
      run: |
        file out/escargot
        strip out/escargot
        $RUNNER --engine="./out/escargot" new-es
        mv out/escargot out/escargot-mac64arm
    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: mac64arm-result
        path: out/escargot-mac64arm

  build-linux32:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install Packages
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build libicu-dev
    - name: Build x86
      run: |
        cmake -H. -Bout/ -DCMAKE_SYSTEM_PROCESSOR=x86 $BUILD_OPTIONS
        ninja -Cout/
    - name: Check
      run: |
        file out/escargot
        strip out/escargot
        $RUNNER --engine="./out/escargot" new-es test262
        mv out/escargot out/escargot-linux32
    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: linux32-result
        path: out/escargot-linux32

  build-linux64:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install Packages
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build libicu-dev
    - name: Build x64
      run: |
        cmake -H. -Bout/ $BUILD_OPTIONS
        ninja -Cout/
    - name: Check
      run: |
        file out/escargot
        strip out/escargot
        $RUNNER --engine="./out/escargot" new-es test262
        mv out/escargot out/escargot-linux64
    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: linux64-result
        path: out/escargot-linux64

  build-linux64-debug:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install Packages
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build libicu-dev
    - name: Build x64
      run: |
        cmake -H. -Bout/ -DESCARGOT_MODE=debug -DESCARGOT_TCO=ON -DESCARGOT_TEST=ON -DESCARGOT_OUTPUT=shell -GNinja
        ninja -Cout/
    - name: Check
      run: |
        file out/escargot
        strip out/escargot
        $RUNNER --engine="./out/escargot" new-es
        mv out/escargot out/escargot-linux64-debug
    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: linux64-result-debug
        path: out/escargot-linux64-debug

  build-linux64-wasm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install Packages
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build libicu-dev gcc-multilib g++-multilib
    - name: Build x64
      run: |
        cmake -H. -Bout/ -DESCARGOT_WASM=ON $BUILD_OPTIONS
        ninja -Cout/
    - name: Check
      run: |
        file out/escargot
        strip out/escargot
        $RUNNER --engine="./out/escargot" new-es wasm-js
        mv out/escargot out/escargot-linux64-wasm
    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: linux64-wasm-result 
        path: out/escargot-linux64-wasm

  release:
    needs: [build-mac64, build-mac64arm, build-linux32, build-linux64, build-linux64-wasm, build-linux64-debug]
    runs-on: ubuntu-latest
    steps:
    - name: Download mac64 result
      uses: actions/download-artifact@v4
      with:
        name: mac64-result
        path: artifacts
    - name: Download mac64arm result
      uses: actions/download-artifact@v4
      with:
        name: mac64arm-result
        path: artifacts
    - name: Download linux32 result
      uses: actions/download-artifact@v4
      with:
        name: linux32-result
        path: artifacts
    - name: Download linux64 result
      uses: actions/download-artifact@v4
      with:
        name: linux64-result
        path: artifacts
    - name: Download linux64-debug result
      uses: actions/download-artifact@v4
      with:
        name: linux64-result-debug
        path: artifacts
    - name: Download linux64-wasm result
      uses: actions/download-artifact@v4
      with:
        name: linux64-wasm-result
        path: artifacts
    - name: Upload to release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          artifacts/escargot-*
